# Generated by Django 4.0.1 on 2022-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_alter_phonemodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='username',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
